openapi: "3.1.0"
info:
  version: "3.1.0"
  title: "Biletado assets v3"
  termsOfService: "http://biletado.gitlab.io/"
  contact:
    email: "dh@blaimi.de"
  license:
    name: "Creative Commons Attribution Share Alike 4.0 International"
    identifier: CC-BY-SA-4.0
  # language=markdown
  description: |
    ## changelog
    <table>
    <tr><th><p>version</p></th><th><p>changes</p></th></tr>
    <tr>
    <td valign="top"><p>2.0.0</p></td>
    <td valign="top">
    
    * initial v2 specification
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>2.1.0</p></td>
    <td valign="top">
    
    * filters for superior asset-structure
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>2.1.1</p></td>
    <td valign="top">
    
    * allow esperanto diacritics in patterns beside german umlauts
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>2.1.2</p></td>
    <td valign="top">
    
    * fix pattern for address
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>2.1.3</p></td>
    <td valign="top">
    
    * require property for collections
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>3.0.0</p></td>
    <td valign="top">
    
    * structured addresses for buildings
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>3.0.1</p></td>
    <td valign="top">
    
    * fix routes for v3
    
    </td>
    </tr>
    <tr>
    <td valign="top"><p>3.1.0</p></td>
    <td valign="top">
    
    * allow permanent deletion of assets via parameter
    
    </td>
    </tr>
    </table>
    
    ## TODO
    * set `additionalProperties` or `unevaluatedProperties` to `false` properly
    
    ### v3
    * Etag
    * Pagination
    * PATCH

tags:
  - name: status
    description: information about the API-Status
  - name: buildings
    description: CRUD buildings
  - name: storeys
    description: CRUD storeys
  - name: rooms
    description: CRUD rooms
servers:
  - description: default kind installation
    url: "http://localhost:9090"
  - description: |
      custom server, e.g. for local development.
      Note, that the service must respond to CORS-Requests.
    url: "{scheme}{host}{port}"
    variables:
      scheme:
        default: "http://"
      host:
        default: "localhost"
      port:
        default: ":80"
security: []
components:
  securitySchemes:
    biletado:
      type: oauth2
      x-client-id: angular
      flows:
        authorizationCode:
          authorizationUrl: /auth/realms/biletado/protocol/openid-connect/auth/
          tokenUrl: /auth/realms/biletado/protocol/openid-connect/token/
          scopes: {}
  parameters:
    AssetIdParam:
      in: path
      name: id
      schema:
        type: string
        format: uuid
        pattern: ' ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        minLength: 36
        maxLength: 36
      required: true
      description: uuid of the asset
    IncludeDeletedParam:
      in: query
      name: include_deleted
      schema:
        type: boolean
        default: false
      description: Set this `true` to include deleted assets. Not set or anything else does not return deleted assets.
    DeletePermanentParam:
      in: query
      name: permanent
      schema:
        type: boolean
        default: false
      description: Set this `true` to permanently delete an asset. Not set or anything else defaults to a soft delete.
  schemas:
    # <editor-fold desc="AssetCommon">
    Uuid:
      type: string
      format: uuid
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      minLength: 36
      maxLength: 36
    AssetId:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Uuid'
          description: uuid of the asset
      required:
        - id
    AssetDeletedAt:
      type: object
      properties:
        deleted_at:
          description: The date, when this asset was deleted in [RFC3339 Section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).
          type: string
          format: date-time
          pattern: '^((?:(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2}(?:\.\d+)?))(Z|[\+-]\d{2}:\d{2})?)$'
          minLength: 20
          maxLength: 32
      required:
        - deleted_at
    AssetDeletedAtRestore:
      type: object
      properties:
        deleted_at:
          description: restores an asset when set
          type:
            - "null"
    AssetName:
      type: object
      properties:
        name:
          type: string
          description: the name of the asset. MUST contain printable characters only separated by single spaces.
          pattern: '^([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+ )*([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+)$'
          minLength: 1
    # </editor-fold>
    # <editor-fold desc="Status">
    ApiStatus:
      description: Information about the API-Implementation.
      type: object
      properties:
        authors:
          description: List of all authors of this backend.
          type: array
          items:
            $ref: '#/components/schemas/Author'
          minItems: 1
        api_version:
          description: The exact version of the api implemented by this backend.
          type: string
          # pattern from semver.org
          pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
    Author:
      description: A API-Author. MUST contain printable characters only separated by single spaces.
      type: string
      pattern: '^([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+ )*([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+)$'
      minLength: 1
    HealthReadiness:
      description: |
        `ready: true` if all requirements are fulfilled to serve requests.
        This includes runtime dependencies like database-connections.
      type: object
      properties:
        ready:
          description: if the service is healthy and can serve requests
          type: boolean
      required:
        - ready
    HealthLiveness:
      description: |
        `live: true` if the service is operating.
        This does _not_ include runtime requirements like database-connections.
      type: object
      properties:
        live:
          description: if the service is in full operation mode
          type: boolean
      required:
        - live
    Health:
      description: |
        summary of the healthiness of the service.
        May contain additional details like db-connections-status.
      type: object
      allOf:
        - $ref: '#/components/schemas/HealthReadiness'
        - $ref: '#/components/schemas/HealthLiveness'
        - type: object
          additionalProperties: {}
    # </editor-fold>
    # <editor-fold desc="Error">
    ErrorContainer:
      description: 'An error response for an operation.'
      type: 'object'
      properties:
        errors:
          type: array
          minItems: 0
          maxItems: 100
          description: 'The array of error entries associated with the error response'
          items:
            $ref: '#/components/schemas/Error'
        trace:
          description: 'The error trace information.'
          type: 'string'
          format: 'uuid'
    Error:
      description: 'An error response entry.'
      type: 'object'
      properties:
        code:
          description: 'The error code.'
          type: 'string'
          enum: [ 'bad_request', 'not_authorized', 'no_need_to_know' ]
        message:
          description: 'The error message.'
          type: 'string'
        more_info:
          description: 'Additional info about the error.'
          type: 'string'
    # </editor-fold>
    # <editor-fold desc="Building">
    BuildingPrototype:
      description: non-common properties of a building
      type: object
      allOf:
        - $ref: '#/components/schemas/AssetName'
        - type: object
          properties:
            streetname:
              description: |
                the streetname of the address
              type: string
              pattern: '^([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+ )*([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+)$'
              minLength: 0
              maxLength: 255
            housenumber:
              description: |
                the housenumber of the address
              type: string
              pattern: '^[a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]*$'
              minLength: 0
              maxLength: 255
            country_code:
              description: |
                the country of the address in ISO 3166-1 alpha-2 in lowercase
              type: string
              pattern: '^[a-z]{2}$'
              minLength: 2
              maxLength: 2
            postalcode:
              description: |
                the zip code of the building
              type: string
            city:
              description: |
                the city name of the address
              type: string
              pattern: '^([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+ )*([a-zA-ZäöüÄÖÜßĉĝĥĵŝŭĈĜĤIĴŜŬ0-9-.]+)$'
              minLength: 0
              maxLength: 255
          required:
            - name
            - country_code
            - streetname
            - housenumber
            - city
            - postalcode
    Building:
      description: a full building with all properties.
      allOf:
        - $ref: '#/components/schemas/AssetId'
        - $ref: '#/components/schemas/BuildingPrototype'
    BuildingDeleted:
      description: a deleted building
      allOf:
        - $ref: '#/components/schemas/Building'
        - $ref: '#/components/schemas/AssetDeletedAt'
    BuildingMaybeDeleted:
      description: an active or deleted building
      anyOf:
        - $ref: '#/components/schemas/Building'
        - $ref: '#/components/schemas/BuildingDeleted'
    BuildingReplacement:
      description: change or restore a building
      allOf:
        - $ref: '#/components/schemas/BuildingPrototype'
        - $ref: '#/components/schemas/AssetDeletedAtRestore'
    BuildingCollection:
      description: a collection of buildings within a `buildings` property.
      type: object
      properties:
        buildings:
          $ref: '#/components/schemas/BuildingList'
      required:
        - buildings
    BuildingList:
      description: an arraylist of buildings.
      type: array
      items:
        $ref: '#/components/schemas/BuildingMaybeDeleted'
      minItems: 0
    # </editor-fold>
    # <editor-fold desc="Storey">
    StoreyPrototype:
      description: non-common properties of a storey
      type: object
      allOf:
        - $ref: '#/components/schemas/AssetName'
        - type: object
          properties:
            building_id:
              description: the id of the building this storey is attached to
              $ref: '#/components/schemas/Uuid'
          required:
            - name
            - building_id
    Storey:
      description: a full storey with all properties.
      allOf:
        - $ref: '#/components/schemas/AssetId'
        - $ref: '#/components/schemas/StoreyPrototype'
    StoreyDeleted:
      description: a deleted storey
      allOf:
        - $ref: '#/components/schemas/Storey'
        - $ref: '#/components/schemas/AssetDeletedAt'
    StoreyMaybeDeleted:
      description: an active or deleted storey
      anyOf:
        - $ref: '#/components/schemas/Storey'
        - $ref: '#/components/schemas/StoreyDeleted'
    StoreyReplacement:
      description: change or restore a storey
      allOf:
        - $ref: '#/components/schemas/StoreyPrototype'
        - $ref: '#/components/schemas/AssetDeletedAtRestore'
    StoreyCollection:
      description: a collection of storeys within a `storeys` property.
      type: object
      properties:
        storeys:
          $ref: '#/components/schemas/StoreyList'
      required:
        - storeys
    StoreyList:
      description: an arraylist of storeys.
      type: array
      items:
        $ref: '#/components/schemas/StoreyMaybeDeleted'
      minItems: 0
    # </editor-fold>
    # <editor-fold desc="Room">
    RoomPrototype:
      description: non-common properties of a room
      type: object
      allOf:
        - $ref: '#/components/schemas/AssetName'
        - type: object
          properties:
            storey_id:
              description: the id of the storey this room is attached to
              $ref: '#/components/schemas/Uuid'
          required:
            - name
            - storey_id
    Room:
      description: a full room with all properties.
      allOf:
        - $ref: '#/components/schemas/AssetId'
        - $ref: '#/components/schemas/RoomPrototype'
    RoomDeleted:
      description: a deleted room
      allOf:
        - $ref: '#/components/schemas/Room'
        - $ref: '#/components/schemas/AssetDeletedAt'
    RoomMaybeDeleted:
      description: an active or deleted room
      anyOf:
        - $ref: '#/components/schemas/Room'
        - $ref: '#/components/schemas/RoomDeleted'
    RoomReplacement:
      description: change or restore a room
      allOf:
        - $ref: '#/components/schemas/RoomPrototype'
        - $ref: '#/components/schemas/AssetDeletedAtRestore'
    RoomCollection:
      description: a collection of rooms within a `rooms` property.
      type: object
      properties:
        rooms:
          $ref: '#/components/schemas/RoomList'
      required:
        - rooms
    RoomList:
      description: an arraylist of rooms.
      type: array
      items:
        $ref: '#/components/schemas/RoomMaybeDeleted'
      minItems: 0
    # </editor-fold>
  headers:
    Location:
      schema:
        type: string
        format: uri
paths:
  # <editor-fold desc="/status">
  /api/v3/assets/status:
    get:
      operationId: get_status
      summary: returns information about the backend-service and status
      tags:
        - status
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiStatus'
              examples:
                sample:
                  value:
                    authors:
                      - "Ludwik Lejzer Zamenhof"
                    api_version: "2.0.0"
  # </editor-fold>
  # <editor-fold desc="/health">
  /api/v3/assets/health:
    get:
      operationId: get_health
      tags:
        - status
      summary: health information about the service
      responses:
        "200":
          description: the service can be considered as "live".
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
              examples:
                sample:
                  value:
                    live: true
                    ready: true
                    databases:
                      assets:
                        connected: true
        "503":
          description: the service cannot be considered as "live" and should be replaced or restarted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  /api/v3/assets/health/live:
    get:
      operationId: get_health_live
      tags:
        - status
      summary: liveness information about the service. Can be used for liveness probes.
      responses:
        "200":
          description: The service can be considered as "live".
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthLiveness'
              examples:
                sample:
                  value:
                    live: true
        "503":
          description: the service cannot be considered as "live" and should be replaced or restarted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  /api/v3/assets/health/ready:
    get:
      operationId: get_health_ready
      tags:
        - status
      summary: readiness information about the service. Can be used for readiness probes.
      responses:
        "200":
          description: the service can be considered as "ready".
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthReadiness'
              examples:
                sample:
                  value:
                    ready: true
        "503":
          description: the service cannot be considered as "ready" and should not be used to serve requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  # </editor-fold>
  # <editor-fold desc="/buildings">
  /api/v3/assets/buildings:
    get:
      operationId: get_buildings
      tags:
        - buildings
      summary: get all buildings.
      description: If `include_deleted` is set to `true`, deleted buildings will be included.
      parameters:
        - $ref: '#/components/parameters/IncludeDeletedParam'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingCollection'
              examples:
                sample:
                  value:
                    buildings:
                      - id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                        name: okcidento
                        streetname: "provluda strateto"
                        housenumber: "14"
                        country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                        postalcode: "12345"
                        city: "trial urbo"
                      - name: sude
                        id: cf731505-f4f6-412f-992f-1cf24874bac3
                        streetname: ""
                        housenumber: ""
                        country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                        postalcode: ""
                        city: ""
                        deleted_at: "2023-11-06T05:30:59.000Z"
    post:
      operationId: create_building
      tags:
        - buildings
      summary: create a new building
      description: Create a new building with a prototype and autogenerated id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildingPrototype'
            examples:
              sample:
                value:
                  name: okcidento
                  streetname: "provluda strateto"
                  housenumber: "14"
                  country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                  postalcode: "12345"
                  city: "trial urbo"
      security:
        - biletado: []
      responses:
        "201":
          description: successful operation of creating a new building with the building returned.
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
              examples:
                sample:
                  value:
                    id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                    name: okcidento
                    streetname: "provluda strateto"
                    housenumber: "14"
                    country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                    postalcode: "12345"
                    city: "trial urbo"
        "400":
          description: invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  /api/v3/assets/buildings/{id}:
    parameters:
      - $ref: '#/components/parameters/AssetIdParam'
    get:
      operationId: get_building
      tags:
        - buildings
      summary: get a building by its id
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingMaybeDeleted'
              examples:
                sample:
                  value:
                    id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                    name: okcidento
                    streetname: "provluda strateto"
                    housenumber: "14"
                    country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                    postalcode: "12345"
                    city: "trial urbo"
                deleted:
                  value:
                    name: sude
                    id: cf731505-f4f6-412f-992f-1cf24874bac3
                    streetname: ""
                    housenumber: ""
                    country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                    postalcode: ""
                    city: ""
                    deleted_at: "2023-11-06T05:30:59.000Z"
        "404":
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
    put:
      operationId: replace_building
      tags:
        - buildings
      summary: create, replace and/or restore a building by its id
      description: |
        Replace or create a building by its id.
        * The building must not be deleted or it has to be restored by setting `deleted_at: null`.
        * If the building shall be restored, the prototype must be included (TODO: PATCH-method).
      security:
        - biletado: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildingReplacement'
            examples:
              replace:
                value:
                  name: okcidento
                  streetname: "provluda strateto"
                  housenumber: "14"
                  country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                  postalcode: "12345"
                  city: "trial urbo"
              restore:
                value:
                  name: sude
                  streetname: ""
                  housenumber: ""
                  country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                  postalcode: ""
                  city: ""
                  deleted_at: null
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
              examples:
                sample:
                  value:
                    id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                    name: okcidento
                    streetname: "provluda strateto"
                    housenumber: "14"
                    country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                    postalcode: "12345"
                    city: "trial urbo"
        "201":
          description: successful operation of creating a new building if the uuid could not be found.
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
              examples:
                sample:
                  value:
                    id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                    name: okcidento
                    streetname: "provluda strateto"
                    housenumber: "14"
                    country_code: "eo" # not an ISO 3166-1 alpha-2 country code but ISO 639 language code
                    postalcode: "12345"
                    city: "trial urbo"
        "400":
          description: invalid input. This is also returned, if the building was deleted and a restore is not requested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
    delete:
      operationId: delete_building
      tags:
        - buildings
      summary: soft-delete a building
      description: |
        This sets the `deleted_at` property of a building to the current date-time.
        Once the building is soft-deleted, it is only included in #get_buildings when `include_deleted` is `true`.
        The request MUST fail, if the building still has active, i.e. not deleted storeys attached.
        If the `permanent` parameter is set to `true`, a permanent deletion is performed.
        In this case, the request MUST fail, even if soft deleted storeys are attached.
      parameters:
        - $ref: '#/components/parameters/DeletePermanentParam'
      security:
        - biletado: []
      responses:
        "204":
          description: successful operation
        "400":
          description: deletion not possible because of not deleted storeys or other input errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "404":
          description: not found or already deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  # </editor-fold>
  # <editor-fold desc="/storeys">
  /api/v3/assets/storeys:
    get:
      operationId: get_storeys
      tags:
        - storeys
      summary: get all storeys.
      description: If `include_deleted` is set to `true`, deleted storeys will be included.
      parameters:
        - $ref: '#/components/parameters/IncludeDeletedParam'
        - name: building_id
          in: query
          description: filter the returned storeys by the given building
          schema:
            $ref: '#/components/schemas/Uuid'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreyCollection'
              examples:
                sample:
                  value:
                    storeys:
                      - id: f6536bdf-037e-4ee4-aede-a44358e827c4
                        name: subtegmento
                        building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                      - name: kelo
                        id: d41b784c-86b2-4283-8a2f-e1eab1d980d0
                        building_id: cf731505-f4f6-412f-992f-1cf24874bac3
                        deleted_at: "2023-11-06T05:29:59.000Z"
    post:
      operationId: create_storey
      tags:
        - storeys
      summary: create a new storey
      description: |
        Create a new storey with a prototype.
        * The building must exist and must not be deleted
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreyPrototype'
            examples:
              sample:
                value:
                  name: subtegmento
                  building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
      security:
        - biletado: []
      responses:
        "201":
          description: successful operation of creating a new storey with the storey returned.
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Storey'
              examples:
                sample:
                  value:
                    id: f6536bdf-037e-4ee4-aede-a44358e827c4
                    name: subtegmento
                    building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
        "400":
          description: invalid input or the building does not exist or is in deleted state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  /api/v3/assets/storeys/{id}:
    parameters:
      - $ref: '#/components/parameters/AssetIdParam'
    get:
      operationId: get_storey
      tags:
        - storeys
      summary: get a storey by its id
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreyMaybeDeleted'
              examples:
                sample:
                  value:
                    id: f6536bdf-037e-4ee4-aede-a44358e827c4
                    name: subtegmento
                    building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
                deleted:
                  value:
                    name: kelo
                    id: d41b784c-86b2-4283-8a2f-e1eab1d980d0
                    building_id: cf731505-f4f6-412f-992f-1cf24874bac3
                    deleted_at: "2023-11-06T05:29:59.000Z"
        "404":
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
    put:
      operationId: replace_storey
      tags:
        - storeys
      summary: create, replace and/or restore a storey by its id
      description: |
        Replace a storey by its id.
        * The building must exist and must not be deleted.
        * The storey must not be deleted or it has to be restored by setting `deleted_at: null`.
        * If the storey shall be restored, the prototype must be included (TODO: PATCH-method).
      security:
        - biletado: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreyReplacement'
            examples:
              replace:
                value:
                  name: pinta fundo
                  building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
              restore:
                value:
                  name: kelo
                  building_id: cf731505-f4f6-412f-992f-1cf24874bac3
                  deleted_at: null
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Storey'
              examples:
                sample:
                  value:
                    id: f6536bdf-037e-4ee4-aede-a44358e827c4
                    name: pinta fundo
                    building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
        "201":
          description: successful operation of creating a new storey if the uuid could not be found.
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Storey'
              examples:
                sample:
                  value:
                    id: f6536bdf-037e-4ee4-aede-a44358e827c4
                    name: pinta fundo
                    building_id: 5fcaa865-4148-4553-9ee5-5666fceed56a
        "400":
          description: |
            invalid input. This is also returned,
            * if the storey was deleted and a restore is not requested.
            * if the building does not exist or is in deleted state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
    delete:
      operationId: delete_storey
      tags:
        - storeys
      summary: soft-delete a storey
      description: |
        This sets the `deleted_at` property of a storey to the current date-time.
        Once the storey is soft-deleted, it is only included in #get_storeys when `include_deleted` is `true`.
        The request MUST fail, if the storey still has active rooms attached.
        If the `permanent` parameter is set to `true`, a permanent deletion is performed.
        In this case, the request MUST fail, even if soft deleted rooms are attached.
      parameters:
        - $ref: '#/components/parameters/DeletePermanentParam'
      security:
        - biletado: []
      responses:
        "204":
          description: successful operation
        "400":
          description: deletion not possible because of not deleted rooms or other input errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "404":
          description: not found or already deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  # </editor-fold>
  # <editor-fold desc="/rooms">
  /api/v3/assets/rooms:
    get:
      operationId: get_rooms
      tags:
        - rooms
      summary: get all rooms.
      description: If `include_deleted` is set to `true`, deleted rooms will be included.
      parameters:
        - $ref: '#/components/parameters/IncludeDeletedParam'
        - name: storey_id
          in: query
          description: filter the returned rooms by the given storey
          schema:
            $ref: '#/components/schemas/Uuid'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomCollection'
              examples:
                sample:
                  value:
                    rooms:
                      - id: 44b0a13f-ca5a-4ce1-bd93-bfe874e92bb7
                        name: "200"
                        storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
                      - name: "404"
                        id: c3deae20-baaa-4f2c-931c-fbfea5a6fe6a
                        storey_id: d41b784c-86b2-4283-8a2f-e1eab1d980d0
                        deleted_at: "2023-11-06T05:28:59.000Z"
    post:
      operationId: create_room
      tags:
        - rooms
      summary: create a new room
      description: |
        Create a new room with a prototype.
        * The storey must exist and must not be deleted
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomPrototype'
            examples:
              sample:
                value:
                  name: "200"
                  storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
      security:
        - biletado: []
      responses:
        "201":
          description: successful operation of creating a new room with the room returned.
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
              examples:
                sample:
                  value:
                    id: 44b0a13f-ca5a-4ce1-bd93-bfe874e92bb7
                    name: "200"
                    storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
        "400":
          description: invalid input or the storey does not exist or is in deleted state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  /api/v3/assets/rooms/{id}:
    parameters:
      - $ref: '#/components/parameters/AssetIdParam'
    get:
      operationId: get_room
      tags:
        - rooms
      summary: get a room by its id
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomMaybeDeleted'
              examples:
                sample:
                  value:
                    id: 44b0a13f-ca5a-4ce1-bd93-bfe874e92bb7
                    name: "200"
                    storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
                deleted:
                  value:
                    name: "404"
                    id: c3deae20-baaa-4f2c-931c-fbfea5a6fe6a
                    storey_id: d41b784c-86b2-4283-8a2f-e1eab1d980d0
                    deleted_at: "2023-11-06T05:28:59.000Z"
        "404":
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
    put:
      operationId: replace_room
      tags:
        - rooms
      summary: create, replace and/or restore a room by its id
      description: |
        Replace a room by its id.
        * The storey must exist and must not be deleted.
        * The room must not be deleted or it has to be restored by setting `deleted_at: null`.
        * If the room shall be restored, the prototype must be included (TODO: PATCH-method).
      security:
        - biletado: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomReplacement'
            examples:
              replace:
                value:
                  name: "200a"
                  storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
              restore:
                value:
                  name: "404"
                  storey_id: d41b784c-86b2-4283-8a2f-e1eab1d980d0
                  deleted_at: null
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
              examples:
                sample:
                  value:
                    id: 44b0a13f-ca5a-4ce1-bd93-bfe874e92bb7
                    name: "200a"
                    storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
        "201":
          description: successful operation of creating a new room if the uuid could not be found.
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
              examples:
                sample:
                  value:
                    id: 44b0a13f-ca5a-4ce1-bd93-bfe874e92bb7
                    name: "200a"
                    storey_id: f6536bdf-037e-4ee4-aede-a44358e827c4
        "400":
          description: |
            invalid input. This is also returned,
            * if the room was deleted and a restore is not requested.
            * if the storey does not exist or is in deleted state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
    delete:
      operationId: delete_room
      tags:
        - rooms
      summary: soft-delete a room
      description: |
        This sets the `deleted_at` property of a room to the current date-time.
        Once the room is soft-deleted, it is only included in #get_rooms when `include_deleted` is `true`.
      parameters:
        - $ref: '#/components/parameters/DeletePermanentParam'
      security:
        - biletado: []
      responses:
        "204":
          description: successful operation
        "400":
          description: deletion not possible because of input errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "401":
          description: if no (valid) authentication is given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
        "404":
          description: not found or already deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContainer'
  # </editor-fold>
